topics:
    - {
          topic: "/gb_planner/r0_surface_point_cloud",
          type: "sensor_msgs/msg/PointCloud2",
          queue_size: 100,
      }
    - {
          topic: "/tf",
          type: "tf2_msgs/msg/TFMessage",
          queue_size: 100,
      }
    - {
          topic: "/tf_static",
          type: "tf2_msgs/msg/TFMessage",
          queue_size: 100,
      }